import json
import re
from pprint import pformat
from deepdiff import DeepDiff
from arcana.exceptions import ArcanaError
from arcana.release import install_requires


PROVENANCE_VERSION = '1.0'

ARCANA_DEPENDENCIES = [re.split(r'[><=]+', r)[0] for r in install_requires]


class Record(object):
    """
    A representation of the information required to describe the provenance of
    study derivatives. Records the provenance information relevant to a
    specific session, i.e. the general configuration of the pipeline and file
    checksums|field values of the pipeline inputs used to derive the outputs in
    a given session (or visit, subject, study summary). It also records the
    checksums|values of the outputs in order to detect if they have been
    altered outside of Arcana's management (e.g. manual QC/correction)

    Parameters
    ----------
    prov : dict[str, *]
        A dictionary containing the provenance recorded/to record
    frequency : str
        The frequency of the record
    subject_id : str | None
        The subject ID the record corresponds to. If None can be a per-visit or
        per-study summary
    visit_id : str | None
        The visit ID the record corresponds to. If None can be a per-subject or
        per-study summary
    from_study : str
        Name of the study that the record was generated by
    """

    # For duck-typing with Filesets and Fields
    derived = True

    def __init__(self, prov, frequency, subject_id, visit_id, from_study):
        self._prov = prov
        self._frequency = frequency
        self._subject_id = subject_id
        self._visit_id = visit_id
        self._from_study = from_study

    def __repr__(self):
        return ("{}(pipeline={}, frequency={}, subject_id={}, visit_id={}, "
                "from_study='{}')".format(
                    type(self).__name__, self.prov['name'], self.frequency,
                    self.subject_id, self.visit_id, self.from_study))

    def __eq__(self, other):
        return (self._prov == other._prov and
                self._frequency == other._frequency and
                self._subject_id == other._subject_id and
                self._visit_id == other._visit_id and
                self._from_study == other._from_study)

    @property
    def prov(self):
        return self._prov

    @property
    def inputs(self):
        return self._prov['inputs']

    @property
    def outputs(self):
        return self._prov['outputs']

    @property
    def subject_id(self):
        return self._subject_id

    @property
    def visit_id(self):
        return self._visit_id

    @property
    def pipeline_name(self):
        return self._prov['name']

    @property
    def from_study(self):
        return self._from_study

    @property
    def frequency(self):
        return self._frequency

    @property
    def provenance_version(self):
        return self._provenance_version

    def save(self, path):
        """
        Saves the provenance object to a JSON file, optionally including
        checksums for inputs and outputs (which are initially produced mid-
        run) to insert during the write

        Parameters
        ----------
        path : str
            Path to save the generated JSON file
        inputs : dict[str, str | list[str] | list[list[str]]] | None
            Checksums of all pipeline inputs used by the pipeline. For inputs
            of matching frequency to the output derivative associated with the
            provenance object, the values of the dictionary will be single
            checksums. If the output is of lower frequency they will be lists
            of checksums or in the case of 'per_session' inputs to 'per_study'
            outputs, lists of lists of checksum. They need to be provided here
            if the provenance object was initialised without checksums
        outputs : dict[str, str] | None
            Checksums of all pipeline outputs. They need to be provided here
            if the provenance object was initialised without checksums
        """
        with open(path, 'w') as f:
            try:
                json.dump(self.prov, f, indent=2)
            except TypeError:
                raise ArcanaError(
                    "Could not serialise provenance record dictionary:\n{}"
                    .format(pformat(self.prov)))

    @classmethod
    def load(cls, path, frequency, subject_id, visit_id, from_study):
        """
        Loads a saved provenance object from a JSON file

        Parameters
        ----------
        path : str
            Path to the provenance file
        frequency : str
            The frequency of the record
        subject_id : str | None
            The subject ID of the provenance record
        visit_id : str | None
            The visit ID of the provenance record
        from_study : str
            Name of the study the derivatives were created for

        Returns
        -------
        record : Record
            The loaded provenance record
        """
        with open(path) as f:
            prov = json.load(f)
        return Record(prov, frequency, subject_id, visit_id, from_study)

    def mismatches(self, other, include=None, exclude=None):
        """
        Compares information stored within provenance objects with the
        exception of version information to see if they match. Matches are
        constrained to the paths passed to the 'include' kwarg, with the
        exception of sub-paths passed to the 'exclude' kwarg

        Parameters
        ----------
        other : Provenance
            The provenance object to compare against
        include : list[list[str]] | None
            Paths in the provenance to include in the match
        exclude : list[list[str]] | None
            Paths in the provenance to exclude from the match
        """
        if include is None:
            include = [[]]  # Include everything
        if exclude is None:
            exclude = []  # Don't exclude anything
        diff = DeepDiff(self._prov, other._prov)
        return diff
