import os.path


class Scan(object):

    def __init__(self, name, format=None, processed=False, input=False,  # @ReservedAssignment @IgnorePep8
                 required_format=None):
        """
        Parameters
        ----------
        name : str
            The name of the scan
        format : FileFormat
            The file format used to store the scan. Can be one of the
            recognised formats
        processed : bool
            Whether the scan is acquired from the scanner or processed
            (not including automatic processing done on the scanner)
        input : bool
            Whether the scan is to be used as an "input" to the dataset, i.e.
            one that is external to the ones generated by the dataset pipelines
        required_format : FileFormat
            The format that the scan is expected to be in by the dataset
            pipelines (for "input" scans only)
        """
        assert isinstance(name, basestring)
        assert isinstance(format, ScanFormat)
        self._name = name
        self._format = format
        self._processed = processed
        self._required_format = required_format
        self._input = input

    def __eq__(self, other):
        return (self.name == other.name and self.format == other.format and
                self.processed == other.processed and
                self._required_format == other._required_format)

    def __ne__(self, other):
        return not (self == other)

    @property
    def name(self):
        return self._name

    @property
    def format(self):
        return self._format

    @property
    def converted_format(self):
        if self._required_format is None:
            conv_format = self.format
        else:
            conv_format = self._required_format
        return conv_format

    @property
    def processed(self):
        return self._processed

    @property
    def input(self):
        return self._input

    @property
    def filename(self):
        return self._get_filename(self.format)

    @property
    def converted_filename(self):
        return self._get_filename(self.converted_format)

    def _get_filename(self, format):  # @ReservedAssignment
        ext = format.extension if format is not None else ''
        if ext:
            fname = self.name + '.' + ext
        else:
            fname = self.name
        return fname

    def match(self, filename):
        base, ext = os.path.splitext(filename)
        if base != self.name:
            match = False
        elif ext == self.format.extension or self.format is None:
            match = True
        else:
            match = False
        return match

    def __repr__(self):
        return ("Scan(name='{}', format={}, processed={}, input={})"
                .format(self.name, self.format, self.processed, self.input))


class ScanFormat(object):

    def __init__(self, name, extension):
        self._name = name
        self._extension = extension

    def __repr__(self):
        return "FileFormat(name='{}', extension='{}')".format(self.name,
                                                              self.extension)

    @property
    def name(self):
        return self._name

    @property
    def extension(self):
        return self._extension


nifti_format = ScanFormat(name='nifti', extension='nii')

nifti_gz_format = ScanFormat(name='nifti_gz', extension='nii.gz')

mrtrix_format = ScanFormat(name='mrtrix', extension='mif')

analyze_format = ScanFormat(name='analyze', extension='img')

dicom_format = ScanFormat(name='dicom', extension='')

fsl_bvecs_format = ScanFormat(name='fsl_bvecs', extension='bvec')

fsl_bvals_format = ScanFormat(name='fsl_bvals', extension='bval')

mrtrix_grad_format = ScanFormat(name='mrtrix_grad', extension='b')

matlab_format = ScanFormat(name='matlab', extension='mat')
